In [2]:
!pip install torch torchvision torchaudio

  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
  Using cached networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
  Using cached fsspec-2026.7.0-py3-none-any.whl.metadata (10 kB)
  Using cached pillow-12.3.0-cp314-cp314-macosx_11_0_arm64.whl.metadata (9.1 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.3/127.3 MB 903.4 kB/s  0:01:34 eta 0:00:010:00:04
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 2.0 MB/s  0:00:00m 2.1 MB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.9/679.9 kB 1.4 MB/s  0:00:00m 2.2 MB/s eta 0:00:01
Using cached fsspec-2026.7.0-py3-none-any.whl (206 kB)
Using cached networkx-3.6.1-py3-none-any.whl (2.1 MB)
Using cached pillow-12.3.0-cp314-cp314-macosx_11_0_arm64.whl (4.8 MB)
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 1.3 MB/s  0:00:041.3 MB/s eta 0:00

In [3]:
import torch

In [4]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = torch.FloatTensor([[1,2,3], [4,5,6],[7,8,9]])
print("x = ", x)
print("y = ", y)

x =  tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
y =  tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [ ]:
print("Size: ", x.size())
print("Shape: ", x.shape)
#size와 shape 출력이 동일함.
print("차원(랭크)", x.ndimension())

Size:  torch.Size([3, 3])
Shape:  torch.Size([3, 3])
차원(랭크) 2


In [9]:
print(x.type()) #long타입
print(y.type()) #Float타입
z = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
print(z.type()) #Float타입


torch.LongTensor
torch.FloatTensor
torch.FloatTensor


In [13]:
x0 = x.unsqueeze(0)
print(x0)
print(x0.shape)
x1 = x.unsqueeze(1)
print(x1)
print(x1.shape)
x2 = x.unsqueeze(2)
print(x2)
print(x2.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
torch.Size([1, 3, 3])
tensor([[[1, 2, 3]],

        [[4, 5, 6]],

        [[7, 8, 9]]])
torch.Size([3, 1, 3])
tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]])
torch.Size([3, 3, 1])


In [14]:

x00 = torch.unsqueeze(x, 0)
x01 = torch.unsqueeze(x, 1)
x02 = torch.unsqueeze(x, 2)
print(x00)
print(x00.shape)
print(x01)
print(x01.shape)
print(x02)
print(x02.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
torch.Size([1, 3, 3])
tensor([[[1, 2, 3]],

        [[4, 5, 6]],

        [[7, 8, 9]]])
torch.Size([3, 1, 3])
tensor([[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]])
torch.Size([3, 3, 1])


In [22]:
x4 = x.view(9)
print("x4 = ", x4)
x5 = x.view(1, 3, 3)
print("x5 = ", x5)
x6 = x.view(3, -1) #-1을 넣으면  pc가 알아서 채워줌
print("x6 = ", x6)

x4 =  tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
x5 =  tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
x6 =  tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [29]:
x = torch.FloatTensor([[1, 2], [3, 4], [5, 6]])
w = torch.randn(1, 2, dtype=torch.float)
b = torch.randn(3, 1, dtype=torch.float)
print(x, "\n", w, "\n", b)

result = torch.mm(x, torch.t(w)) + b #mm은 메트릭스 멀티플라이,  t()는 행렬 트렌스포즈
print(result)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]]) 
 tensor([[-0.1128,  0.0528]]) 
 tensor([[-1.3577],
        [-0.4200],
        [ 0.5309]])
tensor([[-1.3649],
        [-0.5471],
        [ 0.2839]])


In [ ]:
w = torch.tensor(1.0, requires_grad=True)
#꼭 requires_grad=True를 써야함

a = w*3
l = a **2
l.backward()

print('l을 w로 미분한 값은', w.grad)

l을 w로 미분한 값은  tensor(18.)


In [35]:
w = torch.tensor([1.0, 2.3], requires_grad=True)
#꼭 requires_grad=True를 써야함

a = w*3
l = a **2
costFunction = l.sum()
print(w)
print(a)
print(l)
costFunction.backward()
#w가 스칼라가 아니고 벡터로 주면 l에 대해서 backward안됨
print('costFunction을 w로 미분한 값은', w.grad)

tensor([1.0000, 2.3000], requires_grad=True)
tensor([3.0000, 6.9000], grad_fn=<MulBackward0>)
tensor([ 9.0000, 47.6100], grad_fn=<PowBackward0>)
costFunction을 w로 미분한 값은 tensor([18.0000, 41.4000])
